- name: variable from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: course
    prompt: Please enter Course name
    private: false
  - name: duration
    prompt: Please enter Course Duration
    private: false
  - name: trainer
    prompt: Please enter Trainer name
  tasks:
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "Course is {{course}}, Duration is {{duration}}, Trainer is {{trainer}}"
