- name: variables form args/cmd_line
  hosts: local
  connection: local
  tasks:
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "Course is {{course}}, Duration is {{duration}}, Trainer is {{trainer}}"