- name: variable Preference
  hosts: local
  connection: local
  vars: # play level variable
    greet: "Play"
  vars_files:
    - course.yml
  vars_prompt:
  - name: greet
    prompt: Enter the value
    private: false
  tasks: #task level
  - name: Print variable
    # vars:
    #   greet: "Task"
    ansible.builtin.debug:
      msg: "Hello from {{greet}}"


#1. Args/command-line
#2. Task 
#3. 