- name: variable Preference
  hosts: local
  connection: local
  # vars: # play level variable
  #   greet: "Play"
  vars_files: #from files
    - course.yml
  # vars_prompt:
  # - name: greet
  #   prompt: Enter the value
  #   private: false
  tasks: #task level
  - name: Print variable
    # vars:
    #   greet: "Task"
    ansible.builtin.debug:
      msg: "Hello from {{greet}}"


#1. Command-line or args
#2. Task level
#3. From file
#4. Prompt
#5. Play level
#6. Inventory
#7. Roles