- name: check entered number is greater than 100 0r not
  hosts: localhost
  # connection: local
  vars:
    num: 20
  # vars_prompt:
  # - name: num
  #   prompt: Please enter number
  #   default: "50"
  #   private: false
  tasks:
  - name: print if Given number greater than 100
    ansible.builtin.debug:
      msg: "Given {{ num }} is greater than 100"
    when: num > 100

  - name: print if Given number less than or equal to 100
    ansible.builtin.debug:
      msg: "Given {{ num }} is less than or equal to 100"
    when: num <= 100